### ISSUE TITLE
缺少 lua51.lib

### ISSUE THREAD

**Issue by cexer** [hilarryxu/eelua#1]
麻烦作者看下：
尝试在vs2008当中构建，把.c文件成.cpp，包含C头文件添加extern "C"，编译成功，链接失败，似乎缺少lua51.lib。

**Comment by hilarryxu** [comment]
> 麻烦作者看下： 尝试在vs2008当中构建，把.c文件成.cpp，包含C头文件添加extern "C"，编译成功，链接失败，似乎缺少lua51.lib。

这里用到了 luajit 库，属于第三方库，你自己网上查下
